version: "3.9"

services:
  lgtm:
    image: grafana/otel-lgtm:latest
    networks:
      - app
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - lgtm-data:/data

networks:
  app:
    driver: bridge

volumes:
  lgtm-data:
