version: "3.9"

services:
  lgtm:
    image: grafana/otel-lgtm:latest
    networks:
      - app
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - lgtm-data:/data
      - ./monitoring/prometheus.yaml:/otel-lgtm/prometheus.yaml
      - ./monitoring/sintropy-engine-dashboard.josn:/otel-lgmt/sintropy-engine-dashboard.json
      - ./monitoring/postgres-dashboard.josn:/otel-lgmt/postgres-dashboard.json
      - ./monitoring/grafana-dashboards.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/grafana-dashboards.yaml

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    networks:
      - app
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_URI=192.168.178.36:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres

networks:
  app:
    driver: bridge

volumes:
  lgtm-data:
