version: "3.9"

services:
  postgres:
    image: ghcr.io/leonfelipecordero/postgres-wal2json:18
    restart: always
    networks:
      - app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:$HOME/postgres/pgdata/data

  sintropy-engine:
    image: ghcr.io/leonfelipecordero/sintropy-engine:latest
    restart: always
    networks:
      - app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=dev
      - MONITORING_HOST=lgtm
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres

networks:
  app:
    driver: bridge

volumes:
  postgres:
