quarkus:
  arc:
    fail-on-intercepted-private-method: false
  application:
    name: sintropy-engine
    version: 0.0.1
  log:
    console:
      format: '%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n'
#      format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n' -- this is how prod will be
    level: INFO
  datasource:
    username: postgres
    password: postgres
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    migrate-at-start: true
  jooq:
    dialect: POSTGRES
  http:
    port: 8080

syen:
  feature-flags:
    with-full-replication: false

"%test":
  quarkus:
    log:
      level: INFO